### ISSUE TITLE
Where should I drop this in Jmeter?

### ISSUE THREAD

**Issue by krishnakanthpps** [vadim-klimov/apache-jmeter-listener-elasticsearch#1]

**Comment by vadimklimov** [comment]
The plugin JAR file shall be placed in **JMeter home/lib/ext/**, all dependencies (here, Gson and Jersey libraries) - in **JMeter home/lib/**.

**Comment by krishnakanthpps** [comment]
I placed it. Yet I dont see the listener showing up in the Jmeter GUI. is there anything specific that I should try doing?

**Comment by vadimklimov** [comment]
If you placed JAR file with listener plugin after you started JMeter, please restart it - libraries are checked at JMeter startup.

Add listener component "Backend Listener" to your test plan, then in configuration for this component, check entries in dropdown list for "Backend Listener implementation". Can you see listener's class name there (vadim.jmeter.listeners.ElasticsearchListener)?

**Comment by krishnakanthpps** [comment]
2016/04/22 19:53:57 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: com/sun/jersey/api/client/filter/ClientFilter
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.apache.jmeter.visualizers.backend.BackendListenerGui.actionPerformed(BackendListenerGui.java:166)
    at javax.swing.JComboBox.fireActionEvent(Unknown Source)
    at javax.swing.JComboBox.setSelectedItem(Unknown Source)
    at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
    at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.filter.ClientFilter
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more

This error after I select the elastic search listener in the dropdown. 

Have placed the Listener4ElasticSearch.jar in the lib/ext and the Gson-2.2.2.jar and jersey.jar in the lib folders and then restarted the JMeter.

**Comment by vadimklimov** [comment]
As I wrote earlier, the plugin implementation depends on Gson and Jersey 1.x libraries, so they shall be downloaded and placed in **JMeter home/lib/** before the plugin can be used.

**Comment by krishnakanthpps** [comment]
Do I need to build the JMeter from source again? Because just by placing the plugin jar does not download any gson or jersey jars in the lib folder. 

Even if I place the jars into the lib folder, I am still getting the same error. 

java.lang.NoClassDefFoundError: com/sun/jersey/api/client/UniformInterfaceException

**Comment by vadimklimov** [comment]
No, no need to rebuild the plugin, you can use the provided compiled and built version.

From an exception, I see it failed to load a class from Jersey library. Which Jersey binaries did you use? I used Jersey 1.19 - precisely, a bundle jersey-bundle-1.19.jar.

**Comment by krishnakanthpps** [comment]
Finally. Awesome. Thanks so much for your help.
