### ISSUE TITLE
Issue with GSON on Ubuntu 16.04 with Jmeter 3.0

### ISSUE THREAD

**Issue by krishnakanthpps** [vadim-klimov/apache-jmeter-listener-elasticsearch#2]
Hi. 

Running this on the Digital Ocean Droplet. Installed JMeter 3.0, ES 2.4 and Kibana 4.4.1

Locally on a windows box, the script works fine. A basic script. 

But on remote Ubuntu 16.04 gives me the following error.

2016/09/07 15:02:11 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at vadim.jmeter.listeners.ElasticsearchListener.handleSampleResults(ElasticsearchListener.java:107)
        at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:269)
        at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:241)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more

When I stop the test and run again, it says ping unsuccessful.

Any ideas?

**Comment by vadimklimov** [comment]
Error details suggest the required dependency (Gson library) is not in place. Can you please check that both the custom plugin and mentioned dependencies (Gson and Jersey 1.x libraries) are placed in corresponding JMeter directory.

Regards,
Vadim

**Comment by krishnakanthpps** [comment]
Did that. But let me check again. 

Get Outlook for Android

On Wed, Sep 7, 2016 at 9:04 PM +0530, "Vadim Klimov" notifications@github.com wrote:

Error details suggest the required dependency (Gson library) is not in place. Can you please check that both the custom plugin and mentioned dependencies (Gson and Jersey 1.x libraries) are placed in corresponding JMeter directory.

Regards,

Vadim

**Comment by krishnakanthpps** [comment]
worked. Not sure how I missed the GSON. So stupid of me.

**Comment by Tanwadh** [comment]
Hi krishnakanthpps,
I am trying to integrate Jmeter with ELK Stack.

So far, I am able to add Elastic Search Listner in jmeter . Also it is connected to Elastic Search server hosted locally. I am able to access ElasticSearch Server using port 9200.

While replaying the test script in jmeter, i am getting the same exception which you were getting.

ERROR – jmeter.JMeter: Uncaught exception: java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
at vadim.jmeter.listeners.ElasticsearchListener.handleSampleResults(ElasticsearchListener.java:107)
at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:269)
at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:241)

Could you please assist on this.

**Comment by krishnakanthpps** [comment]
Place the gson jar file in the /lib/ext folder of the Jmeter.

Let me know if that helps.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by Tanwadh** [comment]
Hi krishnakanthpps,

Thanks for the above info.

Error in jmeter logs has been resolved with above suggestion.

Upon Running the script in jmeter and in parallel ES server is running , i cud see below message on the ElasticSearch.bat. Please find below screenshot for the same.

![image](https://cloud.githubusercontent.com/assets/26563517/25335965/e6f6e608-2912-11e7-8f51-d141f427ac75.png)

1.) Below message lines indicates that index has been created as expected.

[2017-04-24T17:08:26,726][INFO ][o.e.c.m.MetaDataCreateIndexService] [AA908517] [jmeter] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2017-04-24T17:08:27,326][INFO ][o.e.c.m.MetaDataMappingService] [AA908517] [jmeter/JQmhJ1uaTn2VbojPWi-mew] create_mapping [Demo]


2.) Below message line indicates some memory issue. 

[2017-04-24T17:08:43,656][WARN ][o.e.c.r.a.DiskThresholdMonitor] [AA908517] high disk watermark [90%] exceeded on [RZwWlzgTSDO9iL4PYk2tBw][AA908517][C:\Users\twadhawa\Desktop\Projects\Learning\Jmeter\
ELK\elasticsearch-5.3.1\elasticsearch-5.3.1\data\nodes\0] free: 229mb[0.1%], shards will be relocated away from this node

Could you please assist me on this and suggest further steps.

**Comment by krishnakanthpps** [comment]
Thats a warning. You could ignore it. Else get a machine with more memory and CPU.

**Comment by Tanwadh** [comment]
Hi krishnakanthpps,

Thanks for the above info.

While running kibana.bat from same local machine, command prompt window automatically closed instantly.

Is it because of less memory.

What are the next step to set up kibana for viewing the dashboard for jmeter test results.

**Comment by krishnakanthpps** [comment]
Launch command line and start the kibana.bat from.the kibana folder. You might get to see the error message.

Based on that error message we can understand what's the issue.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
